version: "3"
services:
  postgres:
    container_name:  postgres
    image: postgres
    environment:
      POSTGRES_USER: sewah
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres:/dta/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@sewah.io}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      # Port used for the Zipkin UI and HTTP Api
      - "9411:9411"
    networks:
      - postgres
      - spring
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3.9.11-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - postgres
    restart: unless-stopped

  eureka-server:
    image: sewah2012/eureka-service
    container_name: eureka_server
    ports:
      - "8761:8761"
    depends_on:
      - zipkin
    networks:
      - spring
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  gateway-service:
    image: sewah2012/gateway-service
    container_name: gateway-service
    ports:
      - "8585:8585"
    depends_on:
      - zipkin
      - eureka-server
    networks:
      - spring
    environment:
      - SPRING_PROFILES_ACTIVE=docker

#  customer-service:
#    image: sewah2012/customer-service
#    container_name: customer-service
#    ports:
#      - "8585:8585"
#    depends_on:
#      - zipkin
#      - eureka-server
#    networks:
#      - spring


networks:
  postgres:
    driver: bridge
  spring:
    driver: bridge

volumes:
  postgres:
  pgadmin:
