server:
  port: 8080
  servlet:
    context-path: /api/v1


spring:
  application:
    name: customer-service
  datasource:
    username: 'sewah'
    url: jdbc:postgresql://localhost:5432/customer
    password: 'password'
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: 'true'
      hibernate:
        ddl-auto: update
      show-sql: 'true'

