server:
  port: 8080
  servlet:
    context-path: /api/v1


spring:
  application:
    name: customer-service

  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:postgresql://localhost:5432/customerDB
    username: sewah
    password: password
    driverClassName: org.postgresql.Driver
    sql:
      init:
        platform: postgres
#  datasource:
#    username: 'sewah'
#    url: jdbc:postgresql://localhost:5432/customerDB
#    password: 'password'
#    jpa:
#      properties:
#        hibernate:
#          dialect: org.hibernate.dialect.PostgreSQLDialect
#          format_sql: 'true'
#      hibernate:
#        ddl-auto: create-drop
#      show-sql: 'true'

