server:
  port: 8181
  servlet:
    context-path: /api/v1


spring:
  application:
    name: fraud-service

  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/fraudDB
    username: sewah
    password: password
    driverClassName: org.postgresql.Driver
    sql:
      init:
        platform: postgres

