server:
  port: ${PORT:8585}
  servlet:
    context-path: /api/v1
spring:
  application:
    name: gateway-service
  zipkin:
    base-url: ${ZIPKIN_BASE_URL:http://localhost:9411}
  cloud:
    gateway:
      routes:
        - id: customer
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=/api/v1/customers/**


eureka:
  client:
    service-url:
      defaultZone: ${DISCOVERY_SERVER_URL:http://localhost:8761/eureka}
    fetch-registry: true
    register-with-eureka: true
