server:
  port: ${PORT:0}
  servlet:
    context-path: /api/v1


spring:
  application:
    name: fraud-service

  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:postgresql://localhost:5432/fraudDB
    username: sewah
    password: password
    driverClassName: org.postgresql.Driver
    sql:
      init:
        platform: postgres

eureka:
  client:
    service-url:
      defaultZone: ${DISCOVERY_SERVER_URL:http://localhost:8761/eureka}
    fetch-registry: true
    register-with-eureka: true

