server:
  port: 8761

spring:
  application:
    name: eureka-server
  zipkin:
    base-url: ${ZIPKIN_BASE_URL:http://zipkin:9411}
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false

